project_name: nif
release:
  github:
    owner: aricart
    name: nif
  name_template: '{{.Tag}}'
  draft: true
builds:
  - main: ./nif.go
    binary: nif
    goos:
      - linux
      - darwin
    goarch:
      - amd64

dist: build

archive:
  wrap_in_directory: true
  name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: zip

checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'

snapshot:
  name_template: 'dev'

nfpm:
  formats:
    - deb
  bindir: /usr/local/bin
  description: NIF (network interfaces)
  vendor: nats-io
